services:
  - type: web
    name: webhook-panorama
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook.py
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY_HERE
      - key: ASSISTANT_ID
        value: asst_DMeuS5POFB45TroJC0VwUtpS